### ISSUE TITLE
Network error licensing 0.8.9

### ISSUE THREAD

**Issue by Mifgan** [felddy/foundryvtt-docker#240]
# 🐛 Bug Report

Hi! 
I just installed a clean (and first) installation of Foundry 0.8.9 through Docker (felddy-foundryvtt, release-0.8.9 and release) on a Synology DS420+. 
Getting it from the website through the url from within Docker didn't work, so I downloaded the zip to container_cache (succesfully recognised), booted it and filled in my license key. 
Then it showed the EULA... which keeps on spinning after I click Agree. I then tried with a new docker container (and a third and fourth time too haha). 
I did check the FAQ/troubleshooting from Foundry VTT that mentioned that my computer might have a strange name, which it hasn't (just letters for the nas's name, currently feldy-foundryvtt4 for the docker container and foundryvtttest for the folder that /data points too). I did remove the license.json file + rebooted the container (a couple of times).

My whole error log is filled with these errors, making me think it's some kind of network issue?
```UnhandledPromiseRejectionWarning: FetchError: request to https://foundryvtt.com/_api/license/sign/ failed, reason: getaddrinfo EAI_AGAIN foundryvtt.com ```
and
```(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)```

I've installed a local (non-Docker) version on my laptop (same network): works fine. 

When I tried to do reach my hosted Foundry instance through a reverse proxy, I got a 405 Not Allowed error after it spend maybe 2-5 minutes on the EULA after clicking Agree (some sort of time-out)? I first thought it might have been a port forwarding rules issue, hence the use of a reserve proxy (that origin port is open as I use reserve proxy's often on that nas). The nas is currently hosting another public container (ubooquity) that works fine from within or without my network. 

I had very similar reason: getaddrinfo EAI_AGAIN foundryvtt.com errors when I tried to download Foundry through FOUNDRY_RELEASE_URL within my first Docker tryout, after which I downloaded it manually, saved it to /data/container_cache and used a CONTAINER_CACHE environment variable to install it.

When trying to ping it, it seems to be stuck on another process as when I use the arrow keys it shows these instead of going arrow up for the previous command. 
![image](https://user-images.githubusercontent.com/13572985/133128004-6f5bda33-7985-4857-8aa3-7fe42f706218.png)
![image](https://user-images.githubusercontent.com/13572985/133128053-fe7517ac-1eb2-4f38-914a-0c41da9bcf33.png)

My settings are
![image](https://user-images.githubusercontent.com/13572985/133128198-8d635814-c6b9-4483-a91a-818bf15f70be.png)
![image](https://user-images.githubusercontent.com/13572985/133128219-ca489923-88fe-4374-9ee5-e8dd76c75ba3.png)

Thanks in advance!

## To Reproduce

I've tried it through the internal ip:port, through xxx.synology.me + on two different devices + through reserve proxy. 

## Expected behavior

I expect that when I click on Agree, I will get access to my Foundry to start download a system, start a world etc. 
![image](https://user-images.githubusercontent.com/13572985/133128488-63616946-cb1e-46a9-883f-92b2d90f6f5f.png)

## Any helpful log output

Docker log export:
```felddy-foundryvtt4
date,stream,content
2021-09-13 16:51:30,stdout,"(node:50) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
"
2021-09-13 16:51:30,stdout,    at processTicksAndRejections (internal/process/task_queues.js:82:21)

2021-09-13 16:51:30,stdout,    at emitErrorCloseNT (internal/streams/destroy.js:74:3)

2021-09-13 16:51:30,stdout,    at emitErrorNT (internal/streams/destroy.js:106:8)

2021-09-13 16:51:30,stdout,    at TLSSocket.emit (domain.js:470:12)

2021-09-13 16:51:30,stdout,    at TLSSocket.emit (events.js:400:28)

2021-09-13 16:51:30,stdout,    at TLSSocket.socketErrorListener (_http_client.js:475:9)

2021-09-13 16:51:30,stdout,    at ClientRequest.emit (domain.js:470:12)

2021-09-13 16:51:30,stdout,    at ClientRequest.emit (events.js:400:28)

2021-09-13 16:51:30,stdout,    at ClientRequest.<anonymous> (/home/foundry/resources/app/node_modules/node-fetch/lib/index.js:1461:11)

2021-09-13 16:51:30,stdout,"(node:50) UnhandledPromiseRejectionWarning: FetchError: request to https://foundryvtt.com/_api/license/sign/ failed, reason: getaddrinfo EAI_AGAIN foundryvtt.com
"
2021-09-13 16:51:25,stdout,FoundryVTT | 2021-09-13 16:51:25 | [[32minfo[39m] Created client session 1548fe0e8aabe943cee51ee4

2021-09-13 16:23:31,stdout,"(node:50) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
"
2021-09-13 16:23:31,stdout,"(node:50) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
"
2021-09-13 16:23:31,stdout,(Use `node --trace-warnings ...` to show where the warning was created)

2021-09-13 16:23:31,stdout,    at processTicksAndRejections (internal/process/task_queues.js:82:21)

2021-09-13 16:23:31,stdout,    at emitErrorCloseNT (internal/streams/destroy.js:74:3)

2021-09-13 16:23:31,stdout,    at emitErrorNT (internal/streams/destroy.js:106:8)

2021-09-13 16:23:31,stdout,    at TLSSocket.emit (domain.js:470:12)

2021-09-13 16:23:31,stdout,    at TLSSocket.emit (events.js:400:28)

2021-09-13 16:23:31,stdout,    at TLSSocket.socketErrorListener (_http_client.js:475:9)

2021-09-13 16:23:31,stdout,    at ClientRequest.emit (domain.js:470:12)

2021-09-13 16:23:31,stdout,    at ClientRequest.emit (events.js:400:28)

2021-09-13 16:23:31,stdout,    at ClientRequest.<anonymous> (/home/foundry/resources/app/node_modules/node-fetch/lib/index.js:1461:11)

2021-09-13 16:23:31,stdout,"(node:50) UnhandledPromiseRejectionWarning: FetchError: request to https://foundryvtt.com/_api/license/sign/ failed, reason: getaddrinfo EAI_AGAIN foundryvtt.com
"
2021-09-13 16:23:14,stdout,FoundryVTT | 2021-09-13 16:23:14 | [[32minfo[39m] Created client session cb676089406fa8b83e05d186

2021-09-13 16:22:10,stdout,FoundryVTT | 2021-09-13 16:22:10 | [[32minfo[39m] Created client session a82c0c80f6d98a6d6c335613

2021-09-13 16:21:51,stdout,FoundryVTT | 2021-09-13 16:21:51 | [[32minfo[39m] Server started and listening on port 30000

2021-09-13 16:21:46,stdout,FoundryVTT | 2021-09-13 16:21:46 | [[33mwarn[39m] Software license requires signature.

2021-09-13 16:21:46,stdout,}

2021-09-13 16:21:46,stdout,  "adminKey": "****************"

2021-09-13 16:21:46,stdout,"  \"demo\": null,
"
2021-09-13 16:21:46,stdout,"  \"noupdate\": true,
"
2021-09-13 16:21:46,stdout,"  \"isSSL\": false,
"
2021-09-13 16:21:46,stdout,"  \"isNode\": true,
"
2021-09-13 16:21:46,stdout,"  \"isElectron\": false,
"
2021-09-13 16:21:46,stdout,"  \"serviceConfig\": null,
"
2021-09-13 16:21:46,stdout,"  \"world\": null,
"
2021-09-13 16:21:46,stdout,"  \"upnpLeaseDuration\": null,
"
2021-09-13 16:21:46,stdout,"  \"language\": \"en.core\",
"
2021-09-13 16:21:46,stdout,"  \"updateChannel\": \"release\",
"
2021-09-13 16:21:46,stdout,"  \"minifyStaticFiles\": false,
"
2021-09-13 16:21:46,stdout,"  \"proxyPort\": null,
"
2021-09-13 16:21:46,stdout,"  \"proxySSL\": false,
"
2021-09-13 16:21:46,stdout,"  \"passwordSalt\": null,
"
2021-09-13 16:21:46,stdout,"  \"dataPath\": \"/data\",
"
2021-09-13 16:21:46,stdout,"  \"awsConfig\": null,
"
2021-09-13 16:21:46,stdout,"  \"sslKey\": null,
"
2021-09-13 16:21:46,stdout,"  \"sslCert\": null,
"
2021-09-13 16:21:46,stdout,"  \"routePrefix\": null,
"
2021-09-13 16:21:46,stdout,"  \"localHostname\": null,
"
2021-09-13 16:21:46,stdout,"  \"hostname\": null,
"
2021-09-13 16:21:46,stdout,"  \"fullscreen\": false,
"
2021-09-13 16:21:46,stdout,"  \"upnp\": false,
"
2021-09-13 16:21:46,stdout,"  \"port\": 30000,
"
2021-09-13 16:21:46,stdout,{

2021-09-13 16:21:46,stdout,FoundryVTT | 2021-09-13 16:21:46 | [[32minfo[39m] Application Options:

2021-09-13 16:21:46,stdout,FoundryVTT | 2021-09-13 16:21:46 | [[32minfo[39m] Loading data from user directory - /data

2021-09-13 16:21:46,stdout,FoundryVTT | 2021-09-13 16:21:46 | [[32minfo[39m] Foundry Virtual Tabletop - Version 0.8.9

2021-09-13 16:21:46,stdout,FoundryVTT | 2021-09-13 16:21:46 | [[32minfo[39m] Running on Node.js - Version 14.17.5

2021-09-13 16:21:44,stdout,Launcher | 2021-09-13 16:21:44 | [[32minfo[0m] Starting Foundry Virtual Tabletop.

2021-09-13 16:21:44,stdout,Launcher | 2021-09-13 16:21:44 | [[32minfo[0m] Setting 'Admin Access Key'.

2021-09-13 16:21:44,stdout,Launcher | 2021-09-13 16:21:44 | [[32minfo[0m] Generating options.json file.

2021-09-13 16:21:44,stdout,Entrypoint | 2021-09-13 16:21:44 | [[32minfo[0m] Starting launcher with uid:gid as foundry:foundry.

2021-09-13 16:21:44,stdout,Entrypoint | 2021-09-13 16:21:44 | [[32minfo[0m] Setting data directory permissions.

2021-09-13 16:21:44,stdout,Entrypoint | 2021-09-13 16:21:44 | [[33mwarn[0m] Unable to apply a license key since neither a license key nor credentials were provided.  The license key will need to be entered in the browser.

2021-09-13 16:21:44,stdout,Entrypoint | 2021-09-13 16:21:44 | [[32minfo[0m] Installation not yet licensed.

2021-09-13 16:21:43,stdout,Entrypoint | 2021-09-13 16:21:43 | [[32minfo[0m] Preserving release archive file in cache.

2021-09-13 16:21:40,stdout,Entrypoint | 2021-09-13 16:21:40 | [[32minfo[0m] Installing Foundry Virtual Tabletop 0.8.9

2021-09-13 16:21:40,stdout,Entrypoint | 2021-09-13 16:21:40 | [[32minfo[0m] Using CONTAINER_CACHE: /data/container_cache

2021-09-13 16:21:40,stdout,Entrypoint | 2021-09-13 16:21:40 | [[32minfo[0m] No Foundry Virtual Tabletop installation detected.

2021-09-13 16:21:40,stdout,Entrypoint | 2021-09-13 16:21:40 | [[32minfo[0m] Starting felddy/foundryvtt container v0.8.9
```

**Comment by Mifgan** [comment]
I've tried to work from the console this time, but I get the same authentication error
``` Unable to authenticate: request to https://foundryvtt.com/ failed, reason: getaddrinfo EAI_AGAIN foundryvtt.com```

![image](https://user-images.githubusercontent.com/13572985/133228858-754db081-bf11-4e48-9516-ebbef2b16c3f.png)

[This](https://stackoverflow.com/questions/40182121/whats-the-source-of-error-getaddrinfo-eai-again) might point to a DNS time-out issue, so I'll look how I can solve that.

**Comment by Mifgan** [comment]
I tried the risky 'Let's turn the firewall off!' option and it accepted the EULA!
I have no idea which firewall rule was the culprit as 80/443 were open (and 30000, but I plan to close that to use my reverse proxy again).
