### ISSUE TITLE
Startup Crash: uv_os_homedir returned ENOENT (no such file or directory)

### ISSUE THREAD

**Issue by TimPansino** [felddy/foundryvtt-docker#38]
# 🐛 Bug Report

Crash on startup for latest container version.

## To Reproduce

- Pull the latest tag and attempt to start the docker container.

## Expected behavior

The container starts up and runs.

## Any helpful log output

Please run this command:

```bash
docker inspect --format='{{range $k, $v := .Config.Labels}}
    {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
    felddy/foundryvtt:latest
```

Paste the results here:

```console
com.foundryvtt.version = "0.6.4"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2020-06-23 19:14:35+00:00"
org.opencontainers.image.licenses = "CC0-1.0"
org.opencontainers.image.revision = "dab35fcf04e63049d8777b2f3bedb10844c9e33c"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "Foundry Virtual Tabletop"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "0.6.4"
```

Run the container with `CONTAINER_VERBOSE` set to `true`,and paste any useful
log output here:

```console
foundry    | Downloading Foundry release.
foundry    | Connecting to foundryvtt.s3.amazonaws.com (52.218.213.10:443)
foundry    | saving to 'foundryvtt-0.6.4.zip'
foundry    | foundryvtt-0.6.4.zip   4% |*                               | 4342k  0:00:20 ETA
foundry    | foundryvtt-0.6.4.zip  16% |*****                           | 14.9M  0:00:10 ETA
foundry    | foundryvtt-0.6.4.zip  28% |*********                       | 25.6M  0:00:07 ETA
foundry    | foundryvtt-0.6.4.zip  40% |************                    | 36.4M  0:00:05 ETA
foundry    | foundryvtt-0.6.4.zip  51% |****************                | 47.1M  0:00:04 ETA
foundry    | foundryvtt-0.6.4.zip  63% |********************            | 57.8M  0:00:03 ETA
foundry    | foundryvtt-0.6.4.zip  75% |************************        | 68.5M  0:00:02 ETA
foundry    | foundryvtt-0.6.4.zip  87% |***************************     | 79.2M  0:00:01 ETA
foundry    | foundryvtt-0.6.4.zip  98% |******************************* | 89.8M  0:00:00 ETA
foundry    | foundryvtt-0.6.4.zip 100% |********************************| 90.8M  0:00:00 ETA
foundry    | 'foundryvtt-0.6.4.zip' saved
foundry    | Installing Foundry Virtual Tabletop 0.6.4
foundry    | Switching uid:gid to 111:115 and restarting.
foundry    | Starting felddy/foundryvtt container v0.6.4
foundry    | Foundry Virtual Tabletop 0.6.4 is installed.
foundry    | Generating options.json file.
foundry    | Setting 'Admin Access Key'.
foundry    | Starting Foundry Virtual Tabletop.
foundry    | SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_homedir returned ENOENT (no such file or directory)
foundry    |     at _getEnvDataPath (/home/foundry/resources/app/main.js:128:22)
foundry    |     at getPaths (/home/foundry/resources/app/main.js:55:23)
foundry    |     at Object.<anonymous> (/home/foundry/resources/app/main.js:158:18)
foundry    |     at Module._compile (internal/modules/cjs/loader.js:1138:30)
foundry    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
foundry    |     at Module.load (internal/modules/cjs/loader.js:986:32)
foundry    |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
foundry    |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
foundry    |     at internal/main/run_main_module.js:17:47
```

**Comment by TimPansino** [comment]
The offending line is an operating system call to os.homedir(). This is happening because I have the FOUNDRY_UID and FOUNDRY_GID env vars set. The entrypoint script does not create the user and group if they do not exist, causing this error.

**Comment by felddy** [comment]
Thanks for the report.  I'm looking into it. 

I set `FOUNDRY_UID=1000` and `FOUNDRY_GID=100` on my actual server and was not seeing this behavior:

```console
...
foundry_1  | 'foundryvtt-0.6.4.zip' saved
foundry_1  | Installing Foundry Virtual Tabletop 0.6.4
foundry_1  | Switching uid:gid to 1000:100 and restarting.
foundry_1  | Starting felddy/foundryvtt container v0.6.4
foundry_1  | Foundry Virtual Tabletop 0.6.4 is installed.
foundry_1  | Generating options.json file.
foundry_1  | Setting 'Admin Access Key'.
foundry_1  | Starting Foundry Virtual Tabletop.
foundry_1  | FoundryVTT | 2020-06-23 15:19:45 | [info] Foundry Virtual Tabletop - Version 0.6.4
foundry_1  | FoundryVTT | 2020-06-23 15:19:45 | [info] Running on Node.js - Version 12.18.1
foundry_1  | FoundryVTT | 2020-06-23 15:19:45 | [info] Loading data from user directory - /data
foundry_1  | FoundryVTT | 2020-06-23 15:19:45 | [info] Application Options:
...
```

But I am able to reproduce it when I use `FOUNDRY_UID=111` and `FOUNDRY_GID=115`: 🎉 

```console
...
foundry_1  | 'foundryvtt-0.6.4.zip' saved
foundry_1  | Installing Foundry Virtual Tabletop 0.6.4
foundry_1  | Applying license key.
foundry_1  | Switching uid:gid to 111:115 and restarting.
foundry_1  | Starting felddy/foundryvtt container v0.6.4
foundry_1  | Foundry Virtual Tabletop 0.6.4 is installed.
foundry_1  | Generating options.json file.
foundry_1  | Setting 'Admin Access Key'.
foundry_1  | Starting Foundry Virtual Tabletop.
foundry_1  | SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_homedir returned ENOENT (no such file or directory)
foundry_1  |     at _getEnvDataPath (/home/foundry/resources/app/main.js:128:22)
foundry_1  |     at getPaths (/home/foundry/resources/app/main.js:55:23)
foundry_1  |     at Object.<anonymous> (/home/foundry/resources/app/main.js:158:18)
foundry_1  |     at Module._compile (internal/modules/cjs/loader.js:1138:30)
foundry_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
foundry_1  |     at Module.load (internal/modules/cjs/loader.js:986:32)
foundry_1  |     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
foundry_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
foundry_1  |     at internal/main/run_main_module.js:17:47
...
```

Thanks again for reporting this.  I'll get a fix for this up as soon as possible.

**Comment by felddy** [comment]
@TimPansino I just published [`v0.6.4+a` ](https://github.com/felddy/foundryvtt-docker/releases/tag/v0.6.4%2Ba) 

I believe that this will fixes the issue you reported.  After updating I am no longer able to reproduce the error.  

Please `pull` the new image from Docker hub, test, and let me know how it goes.

**Comment by felddy** [comment]
@TimPansino were you able to test the proposed fix?

**Comment by TimPansino** [comment]
I had not, I just tried with the latest build and that is working.

Unrelated but there's an issue with your CONTAINER_PATCHES logic. Seems you're testing a potentially unset variable for truth instead of testing if it's set. I can open a different issue for that though.

```
./entrypoint.sh: line 107: CONTAINER_PATCHES: parameter not set
```
